/*
 * Shared calendar.
 *
 * GET  /api/calendar                          → { events:[…] } mine + shared with me
 * POST /api/calendar {action:'save',  event}  → create or update one (owner only)
 * POST /api/calendar {action:'delete', id}    → remove one (owner only)
 * POST /api/calendar {action:'import', url}   → pull events from a Google Calendar
 *                                               secret iCal address (see below)
 *
 * Identity is the same verified school email as everywhere else — whoami()
 * re-checks the credentials already being sent, and raw emails are only ever
 * returned to the owner of an event (so you can see who you shared it with).
 *
 * ── Google sync, and why it asks for an iCal address ──────────────────────
 * We deliberately do NOT take a Google password, and do not run an OAuth login.
 * Instead you paste the "Secret address in iCal format" from your own Google
 * Calendar settings. That address is a read-only feed for that one calendar; it
 * grants nothing else, it can be regenerated by you at any time, and we never
 * store it — it is used for the single fetch and then dropped. Only the events
 * it returned are saved. The URL is also checked against an allowlist before we
 * fetch it, so this endpoint cannot be pointed at internal addresses.
 *
 * Table (Supabase → SQL editor):
 *   create table calendar_event (
 *     id          text primary key,
 *     owner       text not null,
 *     title       text not null,
 *     starts_at   text not null,          -- YYYY-MM-DD or YYYY-MM-DDTHH:MM
 *     ends_at     text,
 *     all_day     boolean not null default false,
 *     repeat      text not null default 'none',
 *     repeat_until text,
 *     by_day      jsonb not null default '[]',   -- for repeat='bydays': [1,2,5] = Mon/Tue/Fri
 *                                                --   (JS weekday numbers, Sunday = 0)
 *     colour      text not null default 'blue',
 *     notes       text,
 *     shared_with jsonb not null default '[]',
 *     source      text not null default 'user',
 *     created_at  timestamptz not null default now()
 *   );
 *   create index calendar_event_owner_idx on calendar_event (owner);
 *   -- RLS off: only the service-role key touches it.
 */

import { db, whoami } from "./_supabase.js";

const cap = s => s ? s[0].toUpperCase() + s.slice(1).toLowerCase() : s;
function nameFromEmail(email) {
  const local = String(email).split("@")[0];
  const parts = local.split(".").filter(Boolean);
  if (parts.length >= 2) return cap(parts[0]) + " " + cap(parts[1].replace(/\d+$/, ""));
  return cap(local.replace(/\d+$/, "")) || "Someone";
}

const newId = () => Date.now().toString(36) + Math.random().toString(36).slice(2, 8);
const REPEATS = new Set(["none", "daily", "weekdays", "weekly", "fortnightly", "bydays", "monthly", "yearly"]);
const COLOURS = new Set(["blue", "green", "red", "orange", "purple", "teal", "pink", "grey"]);
const MAX_EVENTS = 500;          // per owner, so one account can't fill the table
const MAX_IMPORT = 200;

/* Only these hosts may be fetched, so the import cannot be aimed at an internal
   service. Google's iCal feeds live on calendar.google.com. */
const ICS_HOSTS = new Set(["calendar.google.com", "www.google.com"]);

const clean = (v, n) => String(v == null ? "" : v).slice(0, n).trim();
const isDate = v => /^\d{4}-\d{2}-\d{2}(T\d{2}:\d{2})?$/.test(String(v || ""));

/* weekday picks for repeat='bydays' — whole numbers 0..6 (Sunday = 0), deduped.
   The typeof guard matters: Number(null) and Number('') are both 0, so without
   it a stray null in the array would quietly become "every Sunday". */
const weekdays = v => [...new Set((Array.isArray(v) ? v : [])
  .filter(n => typeof n === "number" || (typeof n === "string" && n.trim() !== ""))
  .map(Number).filter(n => Number.isInteger(n) && n >= 0 && n <= 6))].sort();

function shapeEvent(r, me) {
  const mine = r.owner === me;
  return {
    id: r.id, title: r.title, start: r.starts_at, end: r.ends_at,
    allDay: !!r.all_day, repeat: r.repeat || "none", until: r.repeat_until || null,
    byDay: Array.isArray(r.by_day) ? r.by_day : [],
    colour: r.colour || "blue", notes: r.notes || "", source: r.source || "user",
    mine, owner: mine ? "You" : nameFromEmail(r.owner),
    /* the raw list is the owner's business; everyone else just sees the count */
    sharedWith: mine ? (Array.isArray(r.shared_with) ? r.shared_with : []) : undefined,
    sharedCount: Array.isArray(r.shared_with) ? r.shared_with.length : 0
  };
}

/* ── time zones ───────────────────────────────────────────────────────────
   Google writes most events as a wall-clock time plus a TZID, so we have to
   turn "16:00 in Australia/Sydney" into a real instant before showing it. ICU
   is built into Node, so Intl can do the whole job and we never ship an offset
   table (which would rot every time a DST rule changes). */
const SYDNEY = "Australia/Sydney";
const pad2 = n => String(n).padStart(2, "0");

/* what a UTC instant reads as on a clock in `zone` */
function partsIn(ms, zone) {
  const p = {};
  for (const x of new Intl.DateTimeFormat("en-GB", {
    timeZone: zone, hour12: false, year: "numeric", month: "2-digit",
    day: "2-digit", hour: "2-digit", minute: "2-digit"
  }).formatToParts(new Date(ms))) if (x.type !== "literal") p[x.type] = x.value;
  return { y: +p.year, mo: +p.month, d: +p.day, h: +p.hour % 24, mi: +p.minute };
}
const flatten = p => Date.UTC(p.y, p.mo - 1, p.d, p.h, p.mi);

/* the instant at which a clock in `zone` reads the given wall-clock time.
   Two passes: the first uses the offset at roughly the right moment, the second
   corrects it, which is what makes a DST changeover land on the correct side. */
function fromZone(y, mo, d, h, mi, zone) {
  const want = Date.UTC(y, mo - 1, d, h, mi);
  let ms = want - (flatten(partsIn(want, zone)) - want);
  ms -= flatten(partsIn(ms, zone)) - want;
  return ms;
}

/* ── a deliberately small iCal reader: enough for Google's feeds ────────── */
function parseICS(text) {
  const unfolded = String(text).replace(/\r\n[ \t]/g, "").replace(/\n[ \t]/g, "");
  const out = [];
  const blocks = unfolded.split("BEGIN:VEVENT").slice(1);
  for (const raw of blocks) {
    const body = raw.split("END:VEVENT")[0];
    const field = name => {
      const m = body.match(new RegExp("^" + name + "([^:\\r\\n]*):(.*)$", "mi"));
      return m ? { params: m[1] || "", value: m[2].trim() } : null;
    };
    const summary = field("SUMMARY");
    const dtstart = field("DTSTART");
    if (!summary || !dtstart) continue;
    const dtend = field("DTEND");
    const desc = field("DESCRIPTION");
    const rrule = field("RRULE");

    const toLocal = f => {
      if (!f) return null;
      const v = f.value;
      const d = v.match(/^(\d{4})(\d{2})(\d{2})$/);                 // all-day
      if (d) return { iso: `${d[1]}-${d[2]}-${d[3]}`, allDay: true };
      const t = v.match(/^(\d{4})(\d{2})(\d{2})T(\d{2})(\d{2})/);   // timed
      if (!t) return null;
      const [, Y, M, D, H, Mi] = t;
      /* a "floating" time carries no zone: it means the same clock reading
         everywhere, so it is already what we want to display */
      const asWritten = { iso: `${Y}-${M}-${D}T${H}:${Mi}`, allDay: false };

      const tz = (f.params.match(/TZID="?([^";:]+)/i) || [])[1];
      let ms;
      if (/Z$/.test(v)) ms = Date.UTC(+Y, +M - 1, +D, +H, +Mi);     // explicit UTC
      else if (tz) {
        /* a zone ICU doesn't know throws — better to show the time as written
           than to shift it by a guessed offset */
        try { ms = fromZone(+Y, +M, +D, +H, +Mi, tz); } catch { return asWritten; }
      } else return asWritten;

      const p = partsIn(ms, SYDNEY);   // everyone reading this calendar is here
      return { iso: `${p.y}-${pad2(p.mo)}-${pad2(p.d)}T${pad2(p.h)}:${pad2(p.mi)}`, allDay: false };
    };

    const st = toLocal(dtstart);
    if (!st) continue;
    const en = toLocal(dtend);
    let repeat = "none", byDay = [];
    if (rrule) {
      const f = (rrule.value.match(/FREQ=([A-Z]+)/i) || [])[1];
      const iv = +((rrule.value.match(/INTERVAL=(\d+)/i) || [])[1] || 1);
      if (/DAILY/i.test(f)) repeat = "daily";
      else if (/WEEKLY/i.test(f)) repeat = iv === 2 ? "fortnightly" : "weekly";
      else if (/MONTHLY/i.test(f)) repeat = "monthly";
      else if (/YEARLY/i.test(f)) repeat = "yearly";
      /* a weekly rule listing several days is really "Mon, Wed and Fri" */
      if (repeat === "weekly") {
        const ICAL_DAY = { SU: 0, MO: 1, TU: 2, WE: 3, TH: 4, FR: 5, SA: 6 };
        const days = (rrule.value.match(/BYDAY=([A-Z,\-+0-9]+)/i) || [])[1];
        const picked = weekdays((days || "").split(",")
          .map(d => ICAL_DAY[d.replace(/[^A-Z]/gi, "").toUpperCase()])
          .filter(n => n !== undefined));
        if (picked.length > 1) { repeat = "bydays"; byDay = picked; }
      }
    }
    out.push({
      title: clean(summary.value.replace(/\\,/g, ","), 140) || "(untitled)",
      start: st.iso, end: en ? en.iso : null, allDay: st.allDay,
      repeat, byDay, notes: clean(desc ? desc.value.replace(/\\n/g, " ").replace(/\\,/g, ",") : "", 400)
    });
    if (out.length >= MAX_IMPORT) break;
  }
  return out;
}

export default async function handler(req, res) {
  res.setHeader("Access-Control-Allow-Methods", "GET, POST, OPTIONS");
  res.setHeader("Access-Control-Allow-Headers", "Content-Type, X-School-Email, X-School-Password");
  res.setHeader("Cache-Control", "private, no-store");
  if (req.method === "OPTIONS") return res.status(204).end();

  if (!db) return res.status(503).json({ error: "The calendar is not configured on the server." });
  const me = await whoami(req);
  if (!me) return res.status(401).json({ error: "Sign in to use the calendar." });
  const email = String(me.email).toLowerCase();

  if (req.method === "GET") {
    const { data, error } = await db.from("calendar_event")
      .select("id, owner, title, starts_at, ends_at, all_day, repeat, repeat_until, by_day, colour, notes, shared_with, source")
      .or(`owner.eq.${email},shared_with.cs.["${email}"]`)
      .order("starts_at", { ascending: true }).limit(1000);
    if (error) { console.error("calendar read:", error.message); return res.status(502).json({ error: "Couldn't load the calendar." }); }
    return res.status(200).json({ events: (data || []).map(r => shapeEvent(r, email)) });
  }

  if (req.method !== "POST") return res.status(405).json({ error: "Method not allowed" });

  let body = req.body;
  if (typeof body === "string") { try { body = JSON.parse(body); } catch { body = null; } }
  body = body || {};

  /* ---- delete ---- */
  if (body.action === "delete") {
    const id = clean(body.id, 60);
    const { data: row } = await db.from("calendar_event").select("owner").eq("id", id).maybeSingle();
    if (!row) return res.status(404).json({ error: "That event is already gone." });
    if (row.owner !== email) return res.status(403).json({ error: "You can only delete your own events." });
    const { error } = await db.from("calendar_event").delete().eq("id", id);
    if (error) return res.status(502).json({ error: "Couldn't delete that." });
    return res.status(200).json({ ok: true });
  }

  /* ---- import from a Google iCal address ---- */
  if (body.action === "import") {
    let url;
    try { url = new URL(String(body.url || "").trim()); } catch { return res.status(400).json({ error: "That doesn't look like a web address." }); }
    if (url.protocol !== "https:" || !ICS_HOSTS.has(url.hostname))
      return res.status(400).json({ error: "Only an https address from calendar.google.com is accepted." });

    let text;
    try {
      const r = await fetch(url.toString(), { headers: { "User-Agent": "msc-unofficial-calendar" } });
      if (!r.ok) return res.status(502).json({ error: "Google refused that address (" + r.status + "). Check it is the secret iCal address." });
      text = await r.text();
    } catch { return res.status(502).json({ error: "Couldn't reach Google to read that calendar." }); }
    if (!/BEGIN:VCALENDAR/i.test(text)) return res.status(400).json({ error: "That address didn't return a calendar." });

    const found = parseICS(text);
    if (!found.length) return res.status(200).json({ imported: 0, message: "No events found in that calendar." });

    /* replace anything previously imported, so re-importing updates rather than duplicates */
    await db.from("calendar_event").delete().eq("owner", email).eq("source", "google");
    const rows = found.map(e => ({
      id: newId(), owner: email, title: e.title, starts_at: e.start, ends_at: e.end,
      all_day: e.allDay, repeat: e.repeat, by_day: e.byDay || [], colour: "teal", notes: e.notes,
      shared_with: [], source: "google"
    }));
    const { error } = await db.from("calendar_event").insert(rows);
    if (error) { console.error("calendar import:", error.message); return res.status(502).json({ error: "Couldn't save the imported events." }); }
    /* note: `url` goes out of scope here — it is never written anywhere */
    return res.status(200).json({ imported: rows.length });
  }

  /* ---- create / update ---- */
  const ev = body.event || {};
  const title = clean(ev.title, 140);
  const start = clean(ev.start, 20);
  if (!title) return res.status(400).json({ error: "Give the event a name." });
  if (!isDate(start)) return res.status(400).json({ error: "That start date isn't valid." });
  const end = ev.end && isDate(clean(ev.end, 20)) ? clean(ev.end, 20) : null;
  const until = ev.until && /^\d{4}-\d{2}-\d{2}$/.test(String(ev.until)) ? String(ev.until) : null;
  let repeat = REPEATS.has(ev.repeat) ? ev.repeat : "none";
  const byDay = repeat === "bydays" ? weekdays(ev.byDay) : [];
  if (repeat === "bydays" && !byDay.length) repeat = "weekly";   // no days picked, fall back
  const colour = COLOURS.has(ev.colour) ? ev.colour : "blue";
  const shared = (Array.isArray(ev.sharedWith) ? ev.sharedWith : [])
    .map(x => String(x || "").trim().toLowerCase())
    .filter(x => /^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(x) && x !== email)
    .slice(0, 40);

  const row = {
    owner: email, title, starts_at: start, ends_at: end, all_day: !!ev.allDay,
    repeat, repeat_until: until, by_day: byDay, colour, notes: clean(ev.notes, 600),
    shared_with: shared, source: "user"
  };

  if (ev.id) {
    const { data: existing } = await db.from("calendar_event").select("owner").eq("id", String(ev.id)).maybeSingle();
    if (!existing) return res.status(404).json({ error: "That event no longer exists." });
    if (existing.owner !== email) return res.status(403).json({ error: "You can only edit your own events." });
    const { error } = await db.from("calendar_event").update(row).eq("id", String(ev.id));
    if (error) { console.error("calendar update:", error.message); return res.status(502).json({ error: "Couldn't save that." }); }
    return res.status(200).json({ id: String(ev.id) });
  }

  const { count } = await db.from("calendar_event")
    .select("id", { count: "exact", head: true }).eq("owner", email);
  if ((count || 0) >= MAX_EVENTS) return res.status(400).json({ error: "You've reached the limit of saved events." });

  const id = newId();
  const { error } = await db.from("calendar_event").insert({ id, ...row });
  if (error) { console.error("calendar insert:", error.message); return res.status(502).json({ error: "Couldn't save that." }); }
  return res.status(200).json({ id });
}
